# Generated by Django 5.2.4 on 2025-08-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255, unique=True)),
                ('tur', models.CharField(choices=[('roman', 'Roman'), ('hikaye', 'Hikaye'), ('siir', 'Şiir'), ('biyografi', 'Biyografi'), ('felsefe', 'Felsefe')], max_length=20)),
                ('sayfa_sayisi', models.PositiveIntegerField()),
                ('yayinevi', models.CharField(max_length=255)),
            ],
        ),
    ]
