# Generated by Django 5.2.4 on 2025-08-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='yayin_yili',
            field=models.PositiveIntegerField(default=2025),
            preserve_default=False,
        ),
    ]
