# Generated by Django 5.2.4 on 2025-08-10 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_yayin_yili'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255)),
                ('soyad', models.CharField(max_length=255)),
                ('yas', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='yayin_yili',
            field=models.PositiveIntegerField(default=2025),
        ),
        migrations.AddField(
            model_name='book',
            name='yazar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.author'),
        ),
    ]
